import type { Metadata } from "next";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { GeistSans, GeistMono } from "geist/font";
import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(GeistSans.variable, GeistMono.variable)}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
